configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mozilla%2Ftabstack-ab135cad4c10edc98bbe45d18a1ca23d2d4aa4b2ba2e4554e6991e322ce46231.yml
openapi_spec_hash: 3e8185dfbbd4e83d5f05ded9ce9c5b06
config_hash: 57c64e5e8fe99c1bd7af536d82af4ad9
